### ISSUE TITLE
Potential dependency conflicts between janni and numpy

### ISSUE THREAD

**Issue by NeolithEra** [thorstenwagner/sphire-janni#1]
Hi, as shown in the following full dependency graph of **_janni_**, **_janni_** requires **_numpy ==1.14.5_**, **_janni_** requires **_mrcfile >=1.0.0_** (**_mrcfile 1.1.2_** will be installed, i.e., the newest version satisfying the version constraint), and directed dependency **_mrcfile 1.1.2_** transitively introduces **_numpy >=1.11.0_**.

Obviously, there are multiple version constraints set for **_numpy_** in this project. However, according to pip's _“first found wins”_ installation strategy, **_numpy 1.14.5_** (i.e., the newest version satisfying constraint **_==1.14.5_**) is the actually installed version.

Although the first found package version **_numpy 1.14.5_** just satisfies the later dependency constraint （**_numpy ==1.14.5_**), such installed version is very close to the upper bound of the version constraint of numpy specified by **_mrcfile 1.1.2_**. 

Once **_mrcfile_** upgrades，its newest version will be installed, as **_janni_** does not specify the upper bound of version constraint for **_mrcfile_**. Therefore, it will easily cause a dependency conflict (build failure), if the upgraded **_mrcfile_** version introduces a higher version of **_numpy_**, violating its another version constraint **_==1.14.5_**.

According to the release history of mrcfile, it habitually upgrates Numpy in its recent releases. For instance, mrcfile 1.0.3 upgrated Numpy’s constraint from **_>= 1.10.0 to >=1.11.0_**,mrcfile 1.1.1 upgrated Numpy’s constraint from **_>=1.11.0 to >= 1.11.0,< 1.16.0_**, and mrcfile 1.1.2 upgrated Numpy’s constraint from _**>= 1.11.0,< 1.16.0 to >= 1.11.0**_. 

As such, it is a warm warning of a potential dependency conflict issue for janni.

### Dependency tree
```
janni - 0.1.3
| +- cython(install version:3.0a1 version range:*)
| +- gooeydev(install version:1.0.3.5 version range:>=1.0.3.2)
| | +- colored(install version:1.4.2 version range:>=1.3.93)
| | +- pillow(install version:7.1.1 version range:>=4.3.0)
| | +- psutil(install version:5.7.0 version range:>=5.4.2)
| +- h5py(install version:2.10.0 version range:>=2.5.0)
| +- imagecodecs-lite(install version:2019.2.22 version range:==2019.2.22)
| +- keras(install version:2.2.5 version range:==2.2.5)
| | +- h5py(install version:2.10.0 version range:*)
| | +- keras_applications(install version: version range:>=1.0.8)
| | +- keras_preprocessing(install version: version range:>=1.1.0)
| | +- numpy(install version:1.14.5 version range:>=1.9.1)
| | +- pyyaml(install version:5.3.1 version range:*)
| | +- scipy(install version:1.2.3 version range:>=0.14)
| | +- six(install version:1.14.0 version range:>=1.9.0)
| +- mrcfile(install version:1.1.2 version range:>=1.0.0)
| | +- numpy(install version:1.14.5 version range:>=1.11.0)
| +- numpy(install version:1.14.5 version range:==1.14.5)
| +- pillow(install version:7.1.1 version range:>=6.0.0)
| +- tifffile(install version:2019.7.2 version range:==2019.7.2)
| +- wxpython(install version:4.0.4 version range:==4.0.4)
| | +- pillow(install version:7.1.1 version range:*)
| | +- six(install version:1.14.0 version range:*)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution
1.	Loosen the version range of **_numpy_** to be **_>=1.14.5_**.
2.	Remove your direct dependency **_numpy_**, and use the **_numpy_** transitively introduced by **_mrcfile_**.
3.	Change your direct dependency **_mrcfile_** to be **_>=1.0.0，<=1.1.2_**.
@thorstenwagner  Which solution do you prefer, 1 ,2or 3?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by thorstenwagner** [comment]
Hi @NeolithEra ! Thanks for reporting this. I would prefer solution 3. I will update numpy and mrcfile soon when I switch to tensorflow 2.

A pull request is welcome!

Thanks again!

Best,
Thorsten

**Comment by thorstenwagner** [comment]
I fixed it as suggested! Thanks a lot!
