### ISSUE TITLE
Error after saving changes made on Settings of JANNI 0.2 GUI (Windows OS)

### ISSUE THREAD

**Issue by MCEditor** [thorstenwagner/sphire-janni#2]
Hi there,

Whenever I click the "Start" button after defining the paths on Settings, I get this error.

To be honest, I have 0 knowledge in coding. I just followed the instructions indicated on the SPHIRE website about JANNI. 

I am pretty sure that the file is in the directory so I am wondering why it can't be read by Python. 

![Annotation 2020-10-09 150812](https://user-images.githubusercontent.com/72539755/95553546-5e872800-0a41-11eb-8a78-13f0dd1b3167.png)

**Comment by thorstenwagner** [comment]
Hi MCEditor,

unfortunately JANNI is totally untested on windows. 

I wondering if its a problem with GUI. Could you try to run it via the command line?

Do you have linux machine that you can access?

Best,
Thorsten

**Comment by MCEditor** [comment]
Hi Thorsten,

I didn't expect to get an answer quickly.  Thanks for replying immediately!

Sadly, I only have a Windows machine with me. 

I did try using the command given on the SPHIRE website to create the config file needed however, I still get an error (is it saying the same thing?)

I am actually confused since the website says that entering the command will _create_ the config file and yet the error says it is trying to _find_ it(?) 

Shall I just give up and move on? lol

![Annotation 2020-10-10 120136](https://user-images.githubusercontent.com/72539755/95645356-bc267d80-0af0-11eb-8d09-8ef4a5833ad3.png)

Thanks,
MCEditor

**Comment by thorstenwagner** [comment]
Hi,
is it possible that the folder ```example``` does not exist?

Please create it. With the next release I will make sure that the folders are created. 
If is exists, can you try to avoid ```~```  and rather specify the full path? Might be a problem on windows machines; On linux it points to your home directory. I think it does not exist in windows.

Let me know if it works.

Best,
Thorsten

**Comment by MCEditor** [comment]
Hello again thorstenwagner,

Good news! I was able to create the **_config_janni.json_** file! I created the _example_ folder however, I didn't exactly follow the command line provided from the SPHIRE website.

- Instead of **_janni_denoise.py config ~/example/config_janni.json --movie_dir ~/example/movies/ --even_dir ~/example/even/ --odd_dir ~/example/odd/_** , 
- I used **_janni_denoise config C:\Users\MyName\example\config_janni.json_**  to create the file. 

I'm still figuring out how to set directory path for movie, even, odd, and final weights. Sadly, I have no idea what command to enter.


Anyway, I skipped the setting of directory for those 3 and headed into the Training part, I believe it only needs the config file(?)

After entering the command **_janni_denoise train config_janni.json -g 0_** , I stumbled on another error telling me that there is a mismatch on the HDF5 library version. 

![Annotation 2020-10-11 103403](https://user-images.githubusercontent.com/72539755/95668978-67950800-0bad-11eb-99e8-60dd36e6da06.png)

I tried installing HDF5 1.10.4 by entering command **_conda install HDF5=1.10.4_** but it has already been installed. 

I appreciate all your help so far! I hope we're close to running the tool properly soon!

Thanks again, 
MCEditor

**Comment by thorstenwagner** [comment]
Won't fix
